export const GET_INTERVIEWERS = "GET_INTERVIEWERS";
export const GET_TOP_INTERVIEWERS = "GET_TOP_INTERVIEWERS";
export const ADD_INTERVIEWER = "ADD_INTERVIEWER";
export const REMOVE_INTERVIEWER = "REMOVE_INTERVIEWER";