export const GET_INTERVIEWERS = "GET_INTERVIEWERS";
export const GET_INTERVIEWERS_COUNT = "GET_INTERVIEWERS_COUNT";
export const GET_TOP_INTERVIEWERS = "GET_TOP_INTERVIEWERS";
export const ADD_INTERVIEWER = "ADD_INTERVIEWER";
export const REMOVE_INTERVIEWER = "REMOVE_INTERVIEWER";
export const REMOVE_INTERVIEWER_SUCCESS = "REMOVE_INTERVIEWER_SUCCESS";
export const UPDATE_INTERVIEWER_PROFILE_OFFLINE = "UPDATE_INTERVIEWER_PROFILE_OFFLINE";
export const UPDATE_INTERVIEWER_ONLINE = "UPDATE_INTERVIEWER_ONLINE";

export const GET_INTERVIEWS = "GET_INTERVIEWS";
export const GET_INTERVIEWS_COUNT = "GET_INTERVIEWS_COUNT";
export const REMOVE_INTERVIEW = "REMOVE_INTERVIEW";

export const GET_CANDIDATES = "GET_CANDIDATES";